language: ruby
rvm:
 - 2.3.0
script:
 - git config --global user.email "kyzminov@gmail.com"
 - git config --global user.name "Ievgen Kuzminov"
 - git config --global push.default simple
 - git clone -b leanpub https://${GH_TOKEN}@github.com/iJackUA/rwdtow.git rwdtow-leanpub --depth=1
 - (cd rwdtow-leanpub; bundle install --gemfile=./Gemfile)
 - (cd rwdtow-leanpub; ./cli convert)
 - (cd rwdtow-leanpub; git add ./manuscript/*)
 - (cd rwdtow-leanpub; git commit -m  "Travis build №$TRAVIS_BUILD_NUMBER, Sync $(date)")
 - (cd rwdtow-leanpub; git push)
git:
  depth: 1
branches:
  only:
   - gh-pages
